### PR TITLE
Added python3-jinja2 library to the python installation

### LINKED ISSUE #121: Add the jinja2 python library to the docker image.
This library is needed so we can write out an index of OCL rules as a markdown file easily.

### PR DESCRIPTION
**Pull request by keith-gray-powereng**
Closes #121

### CODE REVIEW

**Comment by marcadetd** [comment]
I think that it is not a good idea to add to the standard riseclipse docker image all the tools or python libraries needed by the different users.
I will exchange next week with @ADehouck about this.

**Comment by marcadetd** [comment]
Another project may not be necessary, I think a branch is enough, we could use the branch name as a tag on DockerHub. Any idea for the name ? iec ?

**Comment by ADehouck** [comment]
idea for the name : withPythonLibs ?

**Comment by marcadetd** [comment]
The added Python libraries will be those needed by the IEC WG ?

**Comment by keith-gray-powereng** [comment]
What if we use "iec61850-6-3"? My thought is we may need to make more changes beyond just adding python libraries and this name is more general.

**Comment by ADehouck** [comment]
The idea was that other users could also want to use this docker image, not only for "iec61850-6-3"

But if you think other changes will be needed, I am OK with "iec61850-6-3"

**Comment by keith-gray-powereng** [comment]
> The idea was that other users could also want to use this docker image, not only for "iec61850-6-3"
> 
> But if you think other changes will be needed, I am OK with "iec61850-6-3"

Ah, okay, I see. I am open to other ideas as well. I do think we will need more packages, I am thinking specifically of generating the documentation in PDF form.

**Comment by marcadetd** [comment]
> > The idea was that other users could also want to use this docker image, not only for "iec61850-6-3"
> > But if you think other changes will be needed, I am OK with "iec61850-6-3"
> 
> Ah, okay, I see. I am open to other ideas as well. I do think we will need more packages, I am thinking specifically of generating the documentation in PDF form.

So, there will be other tools beside Python librairies. Let's start with "iec61850-6-3", we'll see later if something more general is needed by other users.

**Comment by ADehouck** [comment]
> > > The idea was that other users could also want to use this docker image, not only for "iec61850-6-3"
> > > But if you think other changes will be needed, I am OK with "iec61850-6-3"
> > 
> > 
> > Ah, okay, I see. I am open to other ideas as well. I do think we will need more packages, I am thinking specifically of generating the documentation in PDF form.
> 
> So, there will be other tools beside Python librairies. Let's start with "iec61850-6-3", we'll see later if something more general is needed by other users.

OK, perfect : Thank you

**Comment by keith-gray-powereng** [comment]
@marcadetd are you going to create a branch and then I submit a PR with the updated Dockerfile?

**Comment by marcadetd** [comment]
@ADehouck , @keith-gray-powereng 
Hi,
riseclipse/riseclipse-validator-scl:iec61850-6-3 is available on DockerHub. It contains zip and jinja2.
Please, tell me if it is OK or not.

**Comment by keith-gray-powereng** [comment]
This worked perfectly, thank you. I wonder if there should be some sort of version information appended to the docker tag? Like iec61850-6-3-1.0 or iec61850-6-6-20231107? Just so we can identify exactly which image is being used.

**Pull request merged**
