### PR TITLE
Workflow to commit updated Release version and prepare for next one

### PR DESCRIPTION
**Pull request by SoaAlex**
See this PR: https://github.com/riseclipse/riseclipse-developer/pull/21

### CODE REVIEW

**Comment by SoaAlex** [comment]
Made one last successfull test.
Also changed trigger to master and workflow reference to master
OK for merge, just waiting review aproval.

**Comment by marcadetd** [comment]
As said above, only manual trigger

**Comment by SoaAlex** [comment]
Changed to manual

**Review by marcadetd — APPROVED** [review]

**Comment by marcadetd** [comment]
tag seems not valid ?

**Comment by SoaAlex** [comment]
> tag seems not valid ?

I didn't catch it my bad.

It's because I merged 2 actions but the next one was using outputs from the previous one which doesn't exist anymore.
Fixed it in new PR.

**Pull request merged**
